version: 2
jobs:
   build:
     docker:
       - image: gebish/ci:v5
     steps:
       - checkout
       - run:
           command: |
              Xvfb :99 -screen 1 1280x1024x16 -nolisten tcp -fbdir /var/run > /dev/null 2>&1 &
              export DISPLAY=:99
              export FIREFOX_VERSION=53.0.3
              ./gradlew --stacktrace --no-daemon check
       - store_artifacts:
           path: build/reports